name: Valenciennes RP

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Activer pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm --version

      - name: Installer les dépendances
        run: pnpm install --no-frozen-lockfile

      - name: Démarrer le bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: node index.js
